# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -ruleid {1}  -id {[BD 41-1306]}  -suppress 
set_msg_config  -ruleid {2}  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.cache/wt [current_project]
set_property parent.project_path C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/bridge/chu_io_map.svh
set_property file_type "Verilog Header" [get_files C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/bridge/chu_io_map.svh]
read_verilog -library xil_defaultlib -sv {
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/new/MLED.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/uart/baud_gen.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/new/bui_mled_core.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/hdl/mmio/mmio_basic/chu_gpi.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/hdl/mmio/mmio_basic/chu_gpo.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/hdl/sys/bridge/chu_mcs_bridge.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/hdl/mmio/mmio_support/chu_mmio_controller.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/hdl/mmio/mmio_basic/chu_timer.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/uart/chu_uart.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/fifo/fifo.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/fifo/fifo_ctrl.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/hdl/sys/subsys/mmio_sys_vanilla.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/fifo/reg_file.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/uart/uart.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/uart/uart_rx.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/uart/uart_tx.sv
  C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/imports/top/mcs_top_vanilla.sv
}
read_ip -quiet C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/cpu.xci
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/bd_0/ip/ip_2/bd_3914_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/bd_0/ip/ip_3/bd_3914_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/bd_0/ip/ip_6/bd_3914_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/bd_0/ip/ip_7/bd_3914_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/bd_0/bd_3914_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/cpu_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/sources_1/ip/cpu/cpu_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/constrs_1/imports/constraint/Nexys4_DDR_chu.xdc
set_property used_in_implementation false [get_files C:/Users/runne/Desktop/Soc_FPGA/Final_Bui/Final/hdl/Final_Bui/Final_Bui.srcs/constrs_1/imports/constraint/Nexys4_DDR_chu.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top mcs_top_vanilla -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mcs_top_vanilla.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mcs_top_vanilla_utilization_synth.rpt -pb mcs_top_vanilla_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
