# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraint/Nexys4_DDR_chu.xdc

# IP: ip/cpu/cpu.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu || ORIG_REF_NAME==cpu} -quiet] -quiet
